PRODUCTOS_SEED = [
    {"titulo": "Reloj Casio F91W", "slug": "reloj-casio-f91w", "precio": 1800,
     "detalle": "Reloj digital clásico, resistente y ligero", "categoria": "Relojes",
     "imagen": "reloj.svg", "stock": 30},
    {"titulo": "Reloj Casio G-Shock", "slug": "reloj-casio-g-shock", "precio": 7500,
     "detalle": "Reloj deportivo resistente a golpes y agua", "categoria": "Relojes",
     "imagen": "reloj.svg", "stock": 18},
    {"titulo": "Perfume Bleu de Chanel", "slug": "perfume-bleu-de-chanel", "precio": 6500,
     "detalle": "Fragancia masculina elegante y duradera", "categoria": "Perfumes",
     "imagen": "perfume.svg", "stock": 12},
    {"titulo": "Perfume Versace Eros", "slug": "perfume-versace-eros", "precio": 5800,
     "detalle": "Perfume masculino con aroma fuerte y fresco", "categoria": "Perfumes",
     "imagen": "perfume.svg", "stock": 15},
    {"titulo": "Perfume Good Girl", "slug": "perfume-good-girl", "precio": 6200,
     "detalle": "Perfume femenino con aroma dulce y sofisticado", "categoria": "Perfumes",
     "imagen": "perfume.svg", "stock": 10},
    {"titulo": "Aire acondicionado 12000 BTU", "slug": "aire-acondicionado-12000-btu", "precio": 32000,
     "detalle": "Aire acondicionado inverter ideal para habitaciones", "categoria": "Climatización",
     "imagen": "aire.svg", "stock": 8},
    {"titulo": "Aire acondicionado 18000 BTU", "slug": "aire-acondicionado-18000-btu", "precio": 42000,
     "detalle": "Aire acondicionado potente para espacios medianos", "categoria": "Climatización",
     "imagen": "aire.svg", "stock": 6},
    {"titulo": "Aire acondicionado portátil", "slug": "aire-acondicionado-portatil", "precio": 28000,
     "detalle": "Aire acondicionado fácil de mover entre habitaciones", "categoria": "Climatización",
     "imagen": "aire.svg", "stock": 9},
    {"titulo": "Ventilador de pedestal", "slug": "ventilador-de-pedestal", "precio": 3500,
     "detalle": "Ventilador con altura ajustable y 3 velocidades", "categoria": "Climatización",
     "imagen": "ventilador.svg", "stock": 20},
    {"titulo": "Reloj Casio Edifice", "slug": "reloj-casio-edifice", "precio": 9800,
     "detalle": "Reloj elegante para uso formal", "categoria": "Relojes",
     "imagen": "reloj.svg", "stock": 14},
    {"titulo": "Perfume Dior Sauvage", "slug": "perfume-dior-sauvage", "precio": 7200,
     "detalle": "Fragancia masculina intensa y moderna", "categoria": "Perfumes",
     "imagen": "perfume.svg", "stock": 11},
    {"titulo": "Reloj Casio Vintage", "slug": "reloj-casio-vintage", "precio": 2500,
     "detalle": "Reloj estilo retro muy popular", "categoria": "Relojes",
     "imagen": "reloj.svg", "stock": 22},
    {"titulo": "Difusor de aroma", "slug": "difusor-de-aroma", "precio": 1500,
     "detalle": "Dispositivo para aromatizar espacios", "categoria": "Hogar",
     "imagen": "difusor.svg", "stock": 25},
    {"titulo": "Mini aire acondicionado USB", "slug": "mini-aire-acondicionado-usb", "precio": 4500,
     "detalle": "Aire pequeño ideal para escritorio", "categoria": "Climatización",
     "imagen": "aire.svg", "stock": 17},
    {"titulo": "Set de perfumes mini", "slug": "set-de-perfumes-mini", "precio": 3000,
     "detalle": "Colección de fragancias en tamaño pequeño", "categoria": "Perfumes",
     "imagen": "perfume.svg", "stock": 19},
]
